sudo: required
services:
  - docker

before_install:
  - docker build -t aprilshenk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aprilshenk/docker-react npm run test

language: generic 